- hosts: servers
  tasks: 
    - name: Download Zabbix deb
      get_url: 
        url: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
        dest: /tmp/zabbix.deb

    - name: Install Zabbix deb
      become: yes
      apt:
        deb: /tmp/zabbix.deb
        update_cache: yes

    - name: Install PostgreSQL
      become: yes
      apt:
        name: 
          - postgresql 
          - postgresql-contrib 
          - libpq-dev

    - name: Install pip
      become: yes
      apt:
        name: python3-pip

    - name: Install psycopg2
      become: yes
      pip:
        name: psycopg2 

    - name: Install Zabbix server, frontend, agent 
      become: yes
      apt:
        name: 
          - zabbix-server-pgsql 
          - zabbix-frontend-php 
          - php7.4-pgsql 
          - zabbix-nginx-conf
          - zabbix-agent

    - name: Start PostgreSQL services
      service:
        name: postgresql
        state: started


  # Need to change pipelining=True in ansible.cfg to work    

    - name: Connect and create zabbix user
      become: yes
      become_user: postgres
      postgresql_user:
        name: "zabbix"
        password: "Qwerty@123"
        role_attr_flags: SUPERUSER,CREATEROLE,CREATEDB,INHERIT,LOGIN,REPLICATION,BYPASSRLS

    - name: Create a new database with name "zabbix"
      become: yes
      become_user: postgres
      postgresql_db:
        name: zabbix
        
    

    - name: Restore postgres db
      become: yes
      become_user: postgres
      postgresql_db:
        name: zabbix
        state: restore
        target: /usr/share/doc/zabbix-server-pgsql/create.sql.gz
        
    - name: Replace password in config postgres
      become: yes
      ansible.builtin.replace:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^# DBPassword=$'
        replace: 'DBPassword=Qwerty@123'

    - name: Configure PHP for Zabbix frontend
      become: yes
      ansible.builtin.replace:
        path: /etc/zabbix/nginx.conf
        regexp: '^#        listen          80;$'
        replace: 'listen 8081;'

    - name: Configure Datetime Zone php-fpm
      become: yes
      ansible.builtin.replace:
        path: /etc/zabbix/php-fpm.conf
        regexp: '^; php_value\[date.timezone\] = Europe\/Riga$'
        replace: 'php_value[date.timezone] = Asia/Ho_Chi_Minh'


    - name: Start zabbix services
      become: yes
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      with_items:
        - zabbix-server
        - zabbix-agent
        - nginx
        - php7.4-fpm