- hosts: servers
  tasks: 
    - name: Download Zabbix deb
      get_url:
              url: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
              dest: /tmp/zabbix.deb
    
      
