# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
nodes = [
  { :host => "node1", :box => "generic/ubuntu2004", :gui => false, :ip => "192.168.80.135", :cpu => 1, :ram => 1024 }, 
  { :host => "node2", :box => "generic/ubuntu2004", :gui => false, :ip => "192.168.80.136", :cpu => 1, :ram => 1024 },
 { :host => "node3", :box => "generic/ubuntu2004", :gui => false, :ip => "192.168.80.137", :cpu => 1, :ram => 1024 },
]
Vagrant.configure("2") do |config|
  #config.vm.provider "vmware_desktop" do |vb|
  #end
  nodes.each do |node|
    config.vm.define node[:host] do |config|
      config.vm.box = node[:box]
      config.vm.network "private_network", ip: node[:ip], :netmask => "255.255.255.0"
      config.vm.hostname = "#{node[:host]}"

      config.vm.provider "vmware_desktop" do |v|
        v.gui = node[:gui]
        v.memory = node[:ram]
        v.cpus = node[:cpu]
      end
    end
  end
end
